### PR TITLE
Divide

### PR DESCRIPTION
**Pull request by jyachang**
resolve divide test

### CODE REVIEW

**Comment by RemyVeness** [comment]
I think the issue might be with the _innit_ file? but not sure..

**Review by LewPhan — APPROVED** [review]
Good work!! ;)

**Comment by jyachang** [comment]
finally!
i think i missed the indent and : 

and also i accidentally deleted the __int__.py in the test folder

**Comment by jyachang** [comment]
the code in the template needs to be modified to make the test work

**Comment by jyachang** [comment]
also I was not used to python and forget that it is space sensitive! it makes a huge difference....

**Pull request merged**
